apiVersion: tenants.k8s.att.io/v1
kind: UpdateTenant
metadata:
  name: isbcupd
  labels:
    tenant: isbcupd
spec:
  namespaces:
  - name: isbc-ns-1
    resourcequota:
      name: idbs-rq-1
      cpu: 5
      memory: 2Gi
      pods: 5
  - name: isbc-ns-2
    resourcequota:
      name: isbc-rq-2
      cpu: 1
      memory: 1Gi
      pods: 1
