---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: create-tenant-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: tenants.k8s.att.io/v1
    resource: create-tenants
  childResources:
  - apiVersion: argoproj.io/v1alpha1
    resource: workflows
    updateStrategy:
      method: InPlace
  hooks:
    sync:
      webhook:
        url: http://<webhook_ip>:8001/sync
